<?php
	/* Set up template variables */
	$PAGE_name  = 'Step X';
	$PAGE_title = 'Admin/' . $PAGE_name;
	$PAGE_desc = 'download your export of content in the Wordpress-format';
?>
<?php require('_global.php'); ?>
<?php include('_header.php'); ?>


<?php

// The actual code
// ****************************************************************************

	if (ISPOST)
	{

		// Get all pages that has been connected to a Wordpress page, these will get transfered now
		$result = db_getContentDataFromSite( array( 'site' => $PAGE_siteid ) );
		if ( isset( $result ) )
		{
			$date = new DateTime();
			$now = time();

			// Define XML export header as a Heredoc
			$XML_header = <<< EOT
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- generator="Migrate 2 WordPress" created="{$date->format('Y-m-d H:i')}" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>Final Fantasy XII</title><!-- TODO -->
	<link>http://guide.ffuniverse.nu/ff12</link><!-- TODO -->
	<description>Guider på svenska, Final Fantasy Universe</description><!-- TODO -->
	<pubDate>Sat, 11 Apr 2015 12:37:34 +0000</pubDate><!-- TODO -->
	<language>en-US</language><!-- TODO -->
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>http://guide.ffuniverse.nu/</wp:base_site_url><!-- TODO -->
	<wp:base_blog_url>http://guide.ffuniverse.nu/ff12</wp:base_blog_url><!-- TODO -->

	<wp:author>
		<wp:author_id>1</wp:author_id>
		<wp:author_login>admin</wp:author_login>
		<wp:author_email>admin@example.com</wp:author_email>
		<wp:author_display_name><![CDATA[Migrate 2 WordPress]]></wp:author_display_name>
		<wp:author_first_name><![CDATA[Migrate 2 WordPress]]></wp:author_first_name>
		<wp:author_last_name><![CDATA[]]></wp:author_last_name>
	</wp:author>

	<wp:category><!-- TODO - Remove? -->
		<wp:term_id>1</wp:term_id>
		<wp:category_nicename>uncategorized</wp:category_nicename>
		<wp:category_parent></wp:category_parent>
		<wp:cat_name><![CDATA[Uncategorized]]></wp:cat_name>
	</wp:category>
	<wp:category>
		<wp:term_id>2</wp:term_id>
		<wp:category_nicename>uppdatering</wp:category_nicename>
		<wp:category_parent></wp:category_parent>
		<wp:cat_name><![CDATA[Uppdatering]]></wp:cat_name>
	</wp:category>
	<wp:category>
		<wp:term_id>3</wp:term_id>
		<wp:category_nicename>story</wp:category_nicename>
		<wp:category_parent></wp:category_parent>
		<wp:cat_name><![CDATA[Story]]></wp:cat_name>
	</wp:category>
	<wp:category>
		<wp:term_id>4</wp:term_id>
		<wp:category_nicename>disclaimer</wp:category_nicename>
		<wp:category_parent></wp:category_parent>
		<wp:cat_name><![CDATA[Disclaimer]]></wp:cat_name>
	</wp:category>

	<generator>https://github.com/Bellfalasch/Migrate-2-WordPress-2.0/</generator>
EOT;

			// Define XML export footer as a Heredoc
			$XML_footer = <<< EOT
</channel>
</rss>
EOT;

			// Enable function calls in Heredocs
			// http://stackoverflow.com/questions/104516/calling-php-functions-within-heredoc-strings
			function fn($data) {
				return $data;
			}
			$fn = 'fn';

			// Reference: http://devtidbits.com/2011/03/16/the-wordpress-extended-rss-wxr-exportimport-xml-document-format-decoded-and-explained/

			$XML_content = <<< EOT

	<item>
		<title>Utvecklarna</title><!-- TODO -->
		<link>http://guide.ffuniverse.nu/ff12/utvecklarna/</link><!-- TODO -->
		<pubDate>{$fn( date(DATE_RSS, $now) )}</pubDate><!-- DONE? -->
		<pubDate>Fri, 09 Jan 2015 21:14:35 +0000</pubDate>
		<dc:creator><![CDATA[admin]]></dc:creator><!-- TODO -->
		<guid isPermaLink="false">http://localhost/wordpress/utvecklarna/</guid><!-- TODO -->
		<description></description>
		<!-- TODO -->
		<content:encoded><![CDATA[<h2>Hironobu Sakaguchi</h2>
<div class="sidebar_img"><img class="alignnone size-full wp-image-919" src="http://guide.ffuniverse.nu/ff12/wp-content/uploads/sites/11/2015/01/dev_sakaguchi.jpg" alt="dev_sakaguchi" width="129" height="118" /></div>
<p><strong>Roll: </strong>Gud (Final Fantasy-seriens skapare)</p>
<p>Hironobu Sakaguchi skapade denna serie då han skulle avgå från (då) Square. Han hade tidigare gjort bilspel och dylikt åt företaget. Men strax innan hade Enix släppt superhiten Dragon Quest till NES och Sega hade släppt Phantasy Star till Master System. Så Sakaguchi intresserade sig för rollspel och ville som sitt sista spel skapa ett sådant, sin sista fantasi - Final Fantasy. Men han slutade inte utan har fortsatt med serien sen dess. Nu har han dock lämnat Square Enix för att börja på en egen spelserie som ska bli bättre än Final Fantasy. Hans nya företag heter Mist Walker. Det enda han gjort med Final Fantasy XII är att godkänna Matsunos grundidé för spelet.
</p>]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>292</wp:post_id><!-- TODO - remove? -->
		<wp:post_date>{$date->format('Y-m-d H:i:s')}</wp:post_date><!-- DONE? -->
		<wp:post_date>2015-01-09 22:14:35</wp:post_date>
		<wp:post_date_gmt>{$date->format('Y-m-d H:i:s')}</wp:post_date_gmt><!-- DONE? -->
		<wp:post_date_gmt>2015-01-09 21:14:35</wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name>utvecklarna</wp:post_name><!-- TODO -->
		<wp:status>publish</wp:status><!-- TODO - "draft" for content-less pages -->
		<wp:post_parent>0</wp:post_parent><!-- TODO -->
		<wp:menu_order>15</wp:menu_order><!-- TODO -->
		<wp:post_type>page</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:postmeta><!-- TODO - remove? -->
			<wp:meta_key>_edit_last</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta><!-- TODO - remove? -->
			<wp:meta_key>_wp_page_template</wp:meta_key>
			<wp:meta_value><![CDATA[default]]></wp:meta_value>
		</wp:postmeta>
	</item>
EOT;

			while ( $row = $result->fetch_object() )
			{

				$stop = false;

				// Waterfall-choose the best (cleanest) html from the database depending on which is available
				if ( !is_null($row->ready) ) {

					$content = $row->ready;

				} elseif ( !is_null($row->clean) ) {

					$content = $row->clean;

				} elseif ( !is_null($row->tidy) ) {

					$content = $row->tidy;

				} elseif ( !is_null($row->wash) ) {

					$content = $row->wash;

				} elseif ( !is_null($row->content) ) {

					$content = $row->content;

				} else {

					$stop = true;

				}

				if ( !$stop ) {

					// TODO: Generate XML
					// TODO: Use variable $content

				}

			}

			// Test:
			$XML_header = htmlspecialchars($XML_header, ENT_QUOTES, "UTF-8");
			$XML_content = htmlspecialchars($XML_content, ENT_QUOTES, "UTF-8");
			$XML_footer = htmlspecialchars($XML_footer, ENT_QUOTES, "UTF-8");

			echo "<pre>$XML_header
$XML_content
$XML_footer</pre>";

		}

	}

?>

	<form class="well form" action="" method="post">

		<div class="row">
			<div class="span11">

				<p>
					Download XML file with all your pages and content. It can easily be imported into any WordPress installation.
				</p>
				<p>
					Wanna change something? Just go back to the earlier steps and update your content and do another export.
				</p>

				<p class="text-center">
					<input type="submit" name="save_move" value="Download XML" class="btn btn-primary btn-large" />
				</p>

<p>To import this information into a WordPress site follow these steps:</p>
<ol>
<li>Log in to that site as an administrator.</li>
<li>Go to Tools: Import in the WordPress admin panel.</li>
<li>Install the "WordPress" importer from the list.</li>
<li>Activate &amp; Run Importer.</li>
<li>Upload this file using the form provided on that page.</li>
<li>You will first be asked to map the authors in this export file to users</li>
    on the site. For each author, you may choose to map to an</li>
    existing user on the site or to create a new user.</li>
<li>WordPress will then import each of the posts, pages, comments, categories, etc.</li>
    contained in this file into your site.</li>
<ol>

			</div>
		</div>

	</form>

	<h2>Recommended WordPress plugins</h2>
	<p>
		After you've added all your content to WordPress, a huge task remains: to get it production ready.
		To aid you in this task WordPress has many good plugins you can use. Here's a list of a few of them that
		I use to add thumbnails, change page templates, etc, in a jiffy.
	</p>

	<ul class="thumbnails">
		<li class="span4">
			<a href="#" class="thumbnail">
				<img src="" alt="Image" />
			</a>
			<h4>Thumbnail label</h4>
			<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			<p class="text-center">
				<a href="#" class="btn btn-small" target="_blank">Check it out!</a>
			</p>
		</li>
		<li class="span4">
			<a href="#" class="thumbnail">
				<img src="" alt="Image" />
			</a>
			<h4>Thumbnail label</h4>
			<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			<p class="text-center">
				<a href="#" class="btn btn-small" target="_blank">Check it out!</a>
			</p>
		</li>
		<li class="span4">
			<a href="#" class="thumbnail">
				<img src="" alt="Image" />
			</a>
			<h4>Thumbnail label</h4>
			<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			<p class="text-center">
				<a href="#" class="btn btn-small" target="_blank">Check it out!</a>
			</p>
		</li>
		<li class="span4">
			<a href="#" class="thumbnail">
				<img src="" alt="Image" />
			</a>
			<h4>Thumbnail label</h4>
			<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			<p class="text-center">
				<a href="#" class="btn btn-small" target="_blank">Check it out!</a>
			</p>
		</li>
		<li class="span4">
			<a href="#" class="thumbnail">
				<img src="" alt="Image" />
			</a>
			<h4>Thumbnail label</h4>
			<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			<p class="text-center">
				<a href="#" class="btn btn-small" target="_blank">Check it out!</a>
			</p>
		</li>
		<li class="span4">
			<a href="#" class="thumbnail">
				<img src="" alt="Image" />
			</a>
			<h4>Thumbnail label</h4>
			<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			<p class="text-center">
				<a href="#" class="btn btn-small" target="_blank">Check it out!</a>
			</p>
		</li>
	</ul>


<?php require('_footer.php'); ?>
